import Head from "next/head";
import useFirebaseAuth from "@/hooks/useFirebaseAuth";
import Header from "@/components/header";

const Layout = ({ children }) => {
  useFirebaseAuth();
  return (
    <>
      <Head>
        <title>Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <main className="bg-gray-100">{children}</main>
    </>
  );
};

export default Layout;
